name: DeprecatedChecker
main: DeprecatedChecker\Main
version: 1.1.0
api: [5.0.0]
author: ImmoDevs
description: Detects and logs deprecated code usage in PocketMine plugins
website: https://github.com/ImmoDevs/DeprecatedChecker
load: STARTUP
